CPU = stm32
CPU_MODEL = stm32l151cb

# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_rtc
#FEATURES_PROVIDED += periph_rtt
FEATURES_PROVIDED += periph_spi
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_uart periph_uart_modecfg
